name: Windows Build

on: 
  workflow_dispatch: 

env:
  build-dir: build
  build-type: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - name: Base plugin Repo checkout
      uses: actions/checkout@v6
      with:
        path: "main"
        submodules: 'recursive'
        
    - name: Custom VSTSDK Repo checkout
      uses: actions/checkout@v6
      with:
        repository: steinbergmedia/vst3sdk
        path: "vst3sdk"
        ref: 'v3.8.0_build_66'
        submodules: 'recursive'

    - name: Configure CMake
      run: >
        cmake 
        -S ${{ github.workspace }}/main
        -B ${{ github.workspace }}/main/${{ env.build-dir }} 
        -G "Visual Studio 17 2022" 
        -A x64
        -DCMAKE_BUILD_TYPE=${{ env.build-type }}
        -DSMTG_ENABLE_VSTGUI_SUPPORT=ON

    - name: Build
      run: cmake --build ${{ github.workspace }}/main/${{ env.build-dir }}  --config ${{ env.build-type }}
        
    - name: Upload VST
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ matrix.os }}-${{ github.sha }}
        path: build/VST3
